### ISSUE TITLE
Matchmaking tool input interface

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#101]
### Summary
Define how the skill matchmaking service will acquire input data from Worker/Production Profiler and the Virtual Catalogue.

### Intended outcome
An interface design and possibly some code scaffolding to show the design will work. If Matchmaker reads its inputs from a DB, this could be as simple as designing an initial **high-level** schema---e.g. core tables and relations, but no details about columns, etc.

**Comment by kostasgrevenitis** [comment]
1. First version implemented http://awegnoweeadsgdase.s3-website-eu-west-1.amazonaws.com/workerprofiler/index.html
2. The rest of the activities here https://github.com/c0c0n3/kitt4sme.live/issues/115
