### ISSUE TITLE
D2.4 EC reviewers recommendation

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#103]
### Summary
The EC reviewers recommended

> to explain how security and privacy will be validated in the project, in particular end-to-end privacy and security (i.e. third party policies, multi-tenancy data privacy, etc.).
> A table of risks vs. measures addressed in the project would be useful

We should probably address that in D2.4. 

### Intended outcome
D2.4 contains a section about security & privacy validation as well as a table of risks & mitigation actions.

### How will it work?
EC reviewers will be able to find the info they asked for in D2.4.

**Comment by c0c0n3** [comment]
@rx2dev I don't think we can tackle this in Sprint 4, so I parked it in the backlog for now and will probably move it over to sprint 5 at the end of this iteration.

**Comment by c0c0n3** [comment]
Risk and validation items have already been included in the sections written so far (#99), the rest will make it into the second pass (#107).

**Comment by kostasgrevenitis** [comment]
The D4.2 is already in SUSPI's hand for QA review

**Comment by c0c0n3** [comment]
R2M have included a table w/ risks vs measures as suggested by the reviewers in the latest version of d2.4
