### ISSUE TITLE
Dockerise the Worker Profiler

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#121]
### Summary
Package Worker and Production profiler UI in a Docker image so later we can make them available as a Kitt4sme app service.

### Intended outcome
A Docker image gets published on GitHub that contains the Worker/Prod profilers and a Web server to make them accessible over HTTP.

### How will it work?
Set up a GitHub repo with the Worker and Prod profiler code. Implement a Docker file to build the image from the code. Hook up that Docker file into a GitHub CI pipeline to publish the image through a GitHub package.

**Comment by kostasgrevenitis** [comment]
The worker profiler is dockerized. It can be downloaded from here https://hub.docker.com/r/codenception/worker-profiler
