### ISSUE TITLE
Deploy MQTT

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#13]

**Comment by karikolehmainen** [comment]
Mosquitto broker has been deployed to Kitt4SME server with TLS enabled. You need to provide CA certificate on connecting client to the MQTT. E-mail me for getting correct certificate that you can use for connecting to the broker.

**Comment by karikolehmainen** [comment]
Further steps in this task would be to enable OAuth2 authentication using Keycloak for the broker. After that task can be considered ready

**Comment by karikolehmainen** [comment]
Looking at the implementation of MQTT OAuth2 authentication it seems that it requires addition of plugin to Mosquitto broker (https://github.com/iegomez/mosquitto-go-auth) and various configurations for Keycloak (https://github.com/N5GEH/n5geh.tutorials.mosquitto_with_oauth2-) as well as configuring Mosquitto (https://github.com/gewv-tu-dresden/mosquitto-go-auth-oauth2)

This all seems a bit complicated and I am wondering if we should make executive decision to go on with certificate based MQTT authentication and/or username/password as per stock Mosquitto broker... On the other hand tying the broker to Keycloak would be more elegant solution and fall in line with single sign-on approach. Wheter it is worth the time invested is an other matter.

**Comment by c0c0n3** [comment]
closed by #181
