### ISSUE TITLE
Deploy MQTT & UL agent

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#14]

**Comment by karikolehmainen** [comment]
MQTT broker requires CA certificate (and possibly username/password) for connection. CA certificate can be configured with environment variable IOTA_MQTT_CA at docker-compose file. certificate file need to be mapped to docker container as well like so:
`volumes:
            - /etc/cert/ca.crt:/etc/cert/ca.crt`

**Comment by karikolehmainen** [comment]
Basically following Docker compose configuration enables access for IoT Agent to the MQTT broker:
`            - IOTA_MQTT_PROTOCOL=mqtts
            - IOTA_MQTT_PORT=1883
            - IOTA_MQTT_HOST=kitt4sme.collab-cloud.eu # FQDN needs to be used or certificates do not work
            - IOTA_MQTT_USERNAME=<user if used>
            - IOTA_MQTT_PASSWORD=<password if used> 
            - IOTA_PROVIDER_URL=http://iot-agent:4041
            - IOTA_MQTT_CERT=/etc/cert/server.crt
            - IOTA_MQTT_KEY=/etc/cert/server.key
            - IOTA_MQTT_CA=/etc/cert/ca.crt
        volumes:
            - /etc/cert/ca.crt:/etc/cert/ca.crt
            - /etc/cert/server.crt:/etc/cert/server.crt
            - /etc/cert/server.key:/etc/cert/server.key`
