### ISSUE TITLE
Profilers log cleansing

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#156]
### Summary
At the moment the Production Profiler writes Postgres passwords to the log file in clear text. This is just a temporary thing for debugging purposes. So this issue is just a reminder **not** write passwords or other security sensitive data to log files.

### Intended outcome
Before we roll out the profilers in the field trials, the app will get rid of any passwords or other security sensitive data in log messages.

### How will it work?
Implements a log filter or simply mask passwords or any other sensitive data.

[examples]: https://github.com/github/roadmap/issues

**Comment by c0c0n3** [comment]
notice the worker profiler already masks passwords in connection strings as the prod logs show

```log
Worker Profiler connection string: Host=postgres:5432;Username=postgres;Password=abc123;Database=WorkerProfiler
Master ConnectionString => Host=postgres:5432;Username=postgres;Password=******;Database=postgres
```

so the prod profiler can do something similar?

**Comment by kostasgrevenitis** [comment]
The Production Profiler does the same thing!

**Comment by c0c0n3** [comment]
@kostasgrevenitis great!
