### ISSUE TITLE
Problem reportin to Quantumleap

### ISSUE THREAD

**Issue by alvaroo278** [c0c0n3/kitt4sme.live#190]
### Description bug 
I'm trying to post to QL via NGSI-LD, but I can't connect to the Quantumleap (QL) pod. I have an Orion-LD instance with a couple of the same subscriptions, only changing the field "Uri" of "Endpoint".

![image](https://user-images.githubusercontent.com/74782660/217254456-1429c765-38b4-4da5-bbf3-23d6bd234a2e.png)

When an entity changes, I can see it in the echo service, but nothing happens in QL. Also if I see QL logs, I can't see anything. It's so weird.

I tried to do the post manually, and I received a  "Connection timed out error".

![image](https://user-images.githubusercontent.com/74782660/217255567-137f8108-c058-4ca2-a402-d6bf1edec492.png)

Thanks.

**Comment by c0c0n3** [comment]
@alvaroo278 we answered this question over here:
- https://github.com/orchestracities/ngsi-timeseries-api/issues/719
