### ISSUE TITLE
AiQus routing

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#236]
### Is your feature request related to a problem? Please describe.
At the moment AiQus URL routes are straight under the root path `/`

- /ocbv/*
- /static/*
- /ocbv
- /da
- /bl
- /sp
- /docs
- /docs/*
- /openapi.json

### Describe the solution you'd like
We should rebase AiQus's paths so they're all below the `/aiqus` base path.

### Describe alternatives you've considered
Remove the AiQus deployment from our live instance. The AiQus we have is just a demo one, so we could remove it if no one needs it after the May 2023 review.

### Additional context
#235

**Comment by RyanKelvinFord** [comment]
This will not be an issue, because AIQUS includes the descriptors to set up the routes.
