### ISSUE TITLE
TLS Certificate for ArgoCD needs to be updated

### ISSUE THREAD

**Issue by karikolehmainen** [c0c0n3/kitt4sme.live#297]
### Summary
THere is TLS certificate in the file: https://github.com/c0c0n3/kitt4sme.live/blob/main/deployment/mesh-infra/argocd/argocd-cm.yaml that needs to be updated to current
### Intended outcome
Certifiate with expiry date in the future is in place

**Comment by karikolehmainen** [comment]
new certificate merged with pull request  #298

**Comment by c0c0n3** [comment]
@karikolehmainen great, thanks!!

**Comment by c0c0n3** [comment]
@karikolehmainen actually I spoke too soon :-)

it doesn't look like the new cert works...try logging in w/ keycloak. you get redirected back to the argocd login page. here's what i've found in the argocd logs

```
time="2023-05-09T17:19:22Z" level=info msg="Initializing OIDC provider (issuer: https://kitt4sme.collab-cloud.eu/auth/realms/master)"
time="2023-05-09T17:19:22Z" level=warning msg="Failed to verify token: failed to verify token: Failed to query provider \"https://kitt4sme.collab-cloud.eu/auth/realms/master\": Get \"https://kitt4sme.collab-cloud.eu/auth/realms/master/.well-known/openid-configuration\": x509: certificate signed by unknown authority"
```

possibly we uploaded the wrong cert?

**Comment by c0c0n3** [comment]
@karikolehmainen not need to update anymore. in fact, we don't need to configure argocd w/ our tls cert anymore b/c as of

- https://github.com/c0c0n3/kitt4sme.live/issues/231#issuecomment-1542518968

we've got a cert in istio w/ the full ca chain.
