### ISSUE TITLE
Static page url

### ISSUE THREAD

**Issue by RyanKelvinFord** [c0c0n3/kitt4sme.live#326]
We now have https://kitt4sme.collab-cloud.eu/static-page/ available, however it should be accessible via https://kitt4sme.collab-cloud.eu/ to serve as a landing page.

**Comment by RyanKelvinFord** [comment]
Just finalizing and testing the code for this.

**Comment by RyanKelvinFord** [comment]
https://github.com/c0c0n3/kitt4sme.live/pull/334

PR made, will wait for review and merge

**Comment by RyanKelvinFord** [comment]
Waiting for PR to be merged.

**Comment by karikolehmainen** [comment]
Change static page location to be /home  and add column for demo links

**Comment by karikolehmainen** [comment]
New static page is deployed at /home/ -path

Note for the future: If you use other than x86 -based computer to build the docker image, remember to specify x86 platform when defining the base image.
