### ISSUE TITLE
[Datasheets] Fix the UUID in order to have compatibility between Datasheets, Platform Configurator and Adaptive Questionnaire

### ISSUE THREAD

**Issue by karikolehmainen** [c0c0n3/kitt4sme.live#347]
@vcutrona

**Comment by vcutrona** [comment]
> As agreed during the last technical meeting with the coordinator, I focused on the user on-boarding part of the flow, which is the most critical for the next demo.

## Testing setup

**OS** Ubuntu 22.04.3 LTS
**Browser** Firefox 117.0.1 (Mozilla Firefox Snap for Ubuntu)
**Adaptive Questionnaire (AQ) version**: 1.6.6
**Platform Configurator (PC) version**: 0.5.0

## Issues to report

* Completing the AQ survey takes too long (~10 secs to move to the next question). However, the server seems to be slow in general (it takes quite a while to load other applications, e.g., Datasheets and Keycloak -- maybe @karikolehmainen can check this point)
* As per the discussion we had right before the additional review, the AQ final page should be improved to explain:
  * the meaning of the plot (e.g., labels on axes are missing, the semantics of values in [0,1] is not clarified)
  * the next steps for the users (e.g., 'By clicking the "find a kit for your need" button, the SME-oriented Platform Configurator will automatically build a kit featuring the tools that fit your needs the best. Then, you will be automatically redirected to RAMP, where you can start the negotiation phase with the Kit Integrator and further refine the recommended kit.')
* When clicking "find a kit for your need", the user is redirected to RAMP (in my test, to https://ramp.eu/#/service-request/create/a6be2340-a440-4ada-b719-8f5ac5d98401), which however shows a blank page.
  * By checking the console log, I can find an error with code 400 (Bad request) and the message `JSON parse error: Cannot deserialize value of type ``java.util.UUID`` from String "88f87e4602d33f92c67ed078f1b7e0d0": UUID has to be represented by standard 36-char representation`. 
  * The id `88f87e4602d33f92c67ed078f1b7e0d0` is not formatted as a UUID, but its value is read by PC directly from the tool datasheet database (field `information.component_uuid`). Suggestions for @karikolehmainen @RyanKelvinFord :
    *  To update the datasheet database and fix tools IDs to match the UUID format 
    *  To implement a new field validation in the datasheet application so that the user is prevented from entering non-UUID ids in the field "Component UUID"

### Additional context
For details about the request payload as sent by the PC to RAMP, check the 'KitSetDTO' payload at https://kitt4sme.collab-cloud.eu/platform-configurator/docs

**Comment by karikolehmainen** [comment]
Findings from the demo flow:
- Try Adaptive questionnaire takes to RAMP login page, should be something else?
- RAMP login/registration page Look-and-feel adapted to Kitt4SME?
- AQ: Question numbers away cause they cause confusion
- AQ is slow… more resources for VM?
- AQ Internal server error!!
    - 2023-10-02 07:30:26.357 INFO  ch.idsia.adaptive.backend.controller.SurveyController            Request status for token=e8738aa0-788e-465a-b87e-d9779634311c
    - 2023-10-02 07:30:27.078 INFO  ch.idsia.adaptive.backend.controller.SurveyController            User with token=e8738aa0-788e-465a-b87e-d9779634311c request a new question
    - 2023-10-02 07:30:27.412 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/aq].[dispatcherServlet] Servlet.service() for servlet [dispatcherServlet] in context with path [/aq] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Cannot load status: no model for token=e8738aa0-788e-465a-b87e-d9779634311c] with root cause java.lang.IllegalArgumentException: Cannot load status: no model for token=e8738aa0-788e-465a-b87e-d9779634311.           	at ch.idsia.adaptive.backend.services.SurveyManagerService.lambda$getSurvey$1(SurveyManagerService.java:104)at java.base/java.util.Optional.orElseThrow(Optional.java:403
- Platform configurator: 
    - Error on POD logs: 
        - 2023-10-02T10:40:52.721006434+03:00
        - An error occurred while creating a tool from this JSON: {'information': {'component_accronym': 'REORDINIS', 'provider': 'https://www.enterprise-wisdom.com', 'component_name': 'Advanced Reconfiguration Optimization for Resource Distribution and Inventory Integration System'}, 'context': {'industry': ['26'], 'productiveaxis': {'ai_hri': False, 'ai_quality': False, 'ai_manualactivity': True}, 'category': {'reasoning': False, 'decisionmaker': True}, 'features': {}, 'benefits': {'quality': {'1': False, '2': False}, 'operator': {'1': False, '2': False, '3': False}, 'machine': {'1': False, '2': False}, 'production': {'1': True, '2': True}}, 'usecase': {}, 'description': 'Our AI-based Reconfiguration Optimization for Resource Distribution and Inventory Integration System (REORDINIS) addresses the challenge of complex decision-making in production and inventory management. Our solution consists of a set of AI technologies, namely simulation & search algorithms and knowledge-based models & queries, which optimize production plan (re)configuration and inventory management decisions to support operators and engineers. Our solution stands for a reconfiguration framework for production planning and inventory management enabling production plants to be robust, flexible and modular to handle uncertainties in the market, deviations during production, and systems failures and disruptions. '}, 'module_properties': {}, 'skills': {'basic': {}, 'crossfunctional': {}}, 'support': {}, 'technicalrequirements': {'multiuser_support': {'checkbox': False}, 'multienancy_support': {'checkbox': False}, 'gpu_unit': '1', 'ram_unit': '1', 'disk_unit': '1'}, 'datamodel': {'input': {}, 'output': {}, 'datamodel_links': {}}, 'public_endpoints': {}, 'keycloak_id': '7d579e92-6d52-4cd3-addd-cbf3be8a018c'}
        - 'component_uuid'
            - INFO:     127.0.0.6:45045 - "GET /kits-ramp?sid=c2b6b4d6-fed6-4e35-8367-24ccf8157b61 HTTP/1.1" 307 Temporary Redirect

**Comment by vcutrona** [comment]
@karikolehmainen about the PC error:
the given datasheet does not match the current schema; indeed, the key `information.component_uuid` is missing from the json (and thus, it is impossible to create the payload to send to RAMP, which requires the tool uuid).
As I suggested in my previous comment, we need to fix some entries in the database (which possibly have been inserted by using an old version of the datasheets application), otherwise the PC will skip all of them if not providing the required properties (the exception is caught and the datasheet is discarded)

**Comment by karikolehmainen** [comment]
Schema is now fixed in datasheets backend. API is added to retrieve datasheets with valid RAMP UUID's also new datasheets must have valid UUID when created so issue should not arise again. (two out of 15 datasheets currently do not have valid UUID as the components have not been added to martketplace)
