### ISSUE TITLE
[Open calls] Integrate OpenCall-A Software(s) to Live Platform

### ISSUE THREAD

**Issue by karikolehmainen** [c0c0n3/kitt4sme.live#351]

**Comment by kostasgrevenitis** [comment]
The optiplant solution must be up and raining. A routing configuration is missing.

**Comment by RyanKelvinFord** [comment]
https://github.com/c0c0n3/kitt4sme.live/pull/405

PR made currently testing.

**Comment by kostasgrevenitis** [comment]
The application is up and running
