### ISSUE TITLE
Open-calls deployment doc (D2.6)

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#60]
really needed? classified as "Other", so we might get away w/ just delivering the software w/o an accompanying report?

**Comment by c0c0n3** [comment]
also, here's some points I was thinking about if we really have to write this doc.

1. It'd be nice to give advice specific to the folks who'll win the open call tender rather than generic advice on how to deploy a service on our platform.
2. If you agree w/ (1), then we should probably write this doc when we have a better idea about the kind of AI apps open call winners are going to throw at us.
3. We've got to decide who's going to be responsible for the deployment of those AI apps. If it's entirely on us, like the DoA seems to imply, then we can keep the document slim and basically put in there more or less what we told those guys in the past---e.g. open calls webinar. On the other hand, if you think they should do the work, then we should probably give them more info about how platform deployment works---i.e. explain how to whip together code similar to what we currently have in prod: https://github.com/c0c0n3/kitt4sme.live

What do you think?

**Comment by kostasgrevenitis** [comment]
Good morning.

The deliverable is already written. 

One of the two reviewers has already provided comments that we have incorporated in the document. 

So we can deliver both the document and the demo.

**Comment by c0c0n3** [comment]
@c0c0n3 get in touch in touch w/ @kostasgrevenitis to chat about additions to D2.6

1. updated bootstrap procedure
2. mention we're going to provide a VM to test w/
3. simplified test env, no need to run the cluster, just use docker compose
4. provide examples based on https://github.com/c0c0n3/kitt4sme.roughnator/tree/main/tests

**Comment by c0c0n3** [comment]
i. updated: [cluster bootstrap procedure][bootstrap] (#67)
ii. new content: [app deployment tutorial][tute] (#66)

We should massage this content in D2.6 now. The idea is that an open call dev can build the cluster following (i) and then they should be able to deploy an app by tweaking the steps in (ii) according to their use case. Or even better, they should skip (i) and download our VM to get a head start---see #65.


[bootstrap]: https://github.com/c0c0n3/kitt4sme.live/blob/main/docs/bootstrap.md
[tute]: https://github.com/c0c0n3/kitt4sme.live/blob/main/docs/how-to-deploy-app-svc.md

**Comment by kostasgrevenitis** [comment]
The document is updated accordingly, and ready for the final review, before the Quality Check and submission

**Comment by kostasgrevenitis** [comment]
The document is sent to SUPSI for quality review.
