### ISSUE TITLE
[Tracking] Persistence doc (D2.3)

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#61]
really needed? classified as "Other", so we might get away w/ just delivering the software w/o an accompanying report?

**Comment by kostasgrevenitis** [comment]
We need to define:

1. How many database the KITT4SME platform is going to have?
2. Which are those going to be?
3. How will be integrated?
4. Their schemas
5. Who will access to them and why

**Comment by c0c0n3** [comment]
agree!

**Comment by kostasgrevenitis** [comment]
| Partner | System | Database type (NoSQL or Relational) | Database engine | Schema 
|---------|--------|---------------|-----------------|--------|
| Holonix | Worker profiler| NoSQL| MongoDb| TBD | 
| Holonix | Production profiler | NoSQL| MongoDb| TBD |
| SUPSI | FaMS/IM      |TBD         |TBD                |TBD         |TBD         | TBD       
| ROVI| VIQE    |TBD                |TBD                  |TBD         |TBD         |TBD 
| GINGKO    |TBD                |TBD                  |TBD         |TBD         |TBD 
| R2M       | AIQuS      |TBD                |TBD                  |TBD         |TBD         |TBD

**Comment by c0c0n3** [comment]
- to be shared w/ reviewers
- to be uploaded to SUSPI sharepoint (preview, not reviewed yet)

**Comment by kostasgrevenitis** [comment]
Issue sent to Zeki for QA

**Comment by c0c0n3** [comment]
added some clarifications about ngsi persistence as requested by QA: #120
