### ISSUE TITLE
Test VM for open calls

### ISSUE THREAD

**Issue by tassosgeo** [c0c0n3/kitt4sme.live#65]
### Summary
Build a QEMU VM open call devs can use to test basic interaction between their services and the platform infra.

### Intended outcome
An open call dev can download the VM image, spin it up and have a basic KITT4SME cluster instance ready for testing within minutes. They should be able to deploy an AI service as documented in the [deployment tutorial][tute].

### How will it work?
Pack a subset of the whole cluster orchestration and mesh infra in the VM, plus the FIWARE core and DBs (platform infra services) and leave all the rest out. Follow the [cluster bootstrap][bootstrap] procedure to build the VM after having installed Ubuntu (server) 20.04.

[bootstrap]: https://github.com/c0c0n3/kitt4sme.live/blob/main/docs/bootstrap.md
[tute]: https://github.com/c0c0n3/kitt4sme.live/blob/main/docs/how-to-deploy-app-svc.md

**Comment by tassosgeo** [comment]
Created a vagrant vm box from ubuntu2004 base box.
Uploaded in vagrant cloud available in path:  kitt4sme/single_node_cluster 

Proposed configuration (any other vagrant user preferred configuration based on vagrant docs will do):

Vagrantfile:
``` ruby 
# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION= "2"

require 'yaml'

current_dir    = File.dirname(File.expand_path(__FILE__))
config_file    = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = config_file['settings']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = vagrant_config['box']
    config.vm.define vagrant_config['name']
    config.vm.hostname = vagrant_config['name']
    config.vm.network vagrant_config['network'], ip: vagrant_config['ip']
    config.vm.provider vagrant_config['provider'] do |v|
        v.gui = vagrant_config['gui']
        v.name = vagrant_config['name']
        v.memory = vagrant_config['memory']
        v.cpus = vagrant_config['cpus']
    end
end
```

config.yaml:
``` yaml
---
settings:
  provider: 'virtualbox'
  box: 'kitt4sme/single_node_cluster'
  gui: false
  name: 'kitt4sme'
  network: 'public_network'
  ip: '192.168.1.220'       
  memory: 8192
  cpus: 4
```
The ip has to be changed and a replacement of `'public_network'` to `'private_network'` maybe needed according to the desired deployment

Place `Vagrantfile` and `config.yaml` in same directory and from this directory execute the command:
```
vagrant up
```
The vagrant box will be downloaded and the vm will be created on the host.

Currently supported providers:
- Virtualbox

Future providers to support:
- Hyper-V
- Libvirt

**Comment by c0c0n3** [comment]
@tassosgeo good stuff!!
